#!/bin/bash

# Extract required fields using jq
name=$(jq -r '.name' data.json | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
height=$(jq '.height' data.json)
weight=$(jq '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')

# Convert to meters and kilograms
height_m=$(echo "$height / 10" | bc -l)
weight_kg=$(echo "$weight / 10" | bc -l)

# Format and print output
printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n" "$name" "$type" "$weight_kg" "$height_m"
